######### This script generates a table describing the demographics of participants in Study 1
########################################################################################################################### 
###########################################################################################################################  

#####################################
### PACKAGE LOADING 

## Load the relevant libraries. 
## If these packages aren't installed on your machine, type in the following line "install.packages("INSERT PACKAGE NAME ONE AT A TIME")"
library(dplyr)
library(ggplot2)
library(brms)
library(flextable)
library(bayesplot)
library(patchwork)
library(tidyverse)


## Set working directory to current study folder
setwd(file.path(renv::project(), "Study 1")) 

set.seed(3)


#####################################
### DATASET LOADING AND QUICK DATA CHECKS

## Load the dataset
data <- read.csv("Study1_Data.csv")


### Some quick data-checks

## Let's check if any participant did the experiment twice
## Great, no one did!
data %>% count(Anon_PID, sort = TRUE)

## Now we check if anyone didn't finish the study (i.e. were screened out or didn't provide their consent)
## Everyone provided their consent, but one person was screened out!
data %>% count(Consent)
data %>% count(Q_TerminateFlag)
data %>% count(Progress)

## Let's remove this one individual who got screened out
data <- data %>%
  filter(Q_TerminateFlag == "Complete")

## Check if everyone passed the attention check
## Everyone did
data %>% count(Attention.Check.1)

## Two observations in Study 1 didn't see the stimulus (i.e. mental health information) owing to some programming error. 
data %>% filter(stimulus == "")

## Thankfully, as they are both at the end of the chain, we don't have to exclude the whole chain
# Removing these observations at the end of the chain
data <- data %>% filter(stimulus != "")




#####################################
### DATASET FORMATTING FOR ANALYSES

## Cleaning up column names and converting to appropriate data formats so that analytical pipeline runs smoothly
cleaned_dataset <- data.frame(
  PID = as.factor(data$Anon_PID),
  Age = as.numeric(data$Age.Screener),
  SD_Q1 = data$Self.Diagnosis.Qs_1,
  SD_Q2 = data$Self.Diagnosis.Qs_2,
  SD_Q3 = data$Self.Diagnosis.Qs_3,
  SD_Q4 = data$Self.Diagnosis.Qs_4,
  OD_Q1 = data$Other.Diagnosis.Qs_1,
  OD_Q2 = data$Other.Diagnosis.Qs_2,
  Prevalence = as.numeric(data$Q_Prevalence.Rate),
  Treatment = as.numeric(data$Q_Treatment.Rate),
  Sex = as.factor(data$Q5),
  Prior_medication = as.factor(data$Q11),
  Current_Treatment = as.factor(data$Q12),
  NHS_try = as.factor(data$Q13),
  Prior_knowledge_Q1 = data$Q14_1,
  Prior_knowledge_Q2 = data$Q14_2,
  Prior_knowledge_Q3 = data$Q14_3,
  AI_usage = as.factor(data$Q8),
  AI_reason = data$Q9,
  chain = as.factor(data$chain),
  gen = as.factor(data$gen),
  stimulus = as.factor(data$stimulus),
  prompt = as.factor(data$prompt),
  StartDate = data$StartDate
)

### Now, we transform the likert scale options for prior knowledge into numbers now - this would allow for easy summarisation of the data
likert_scale <- c("Never (0 times/week)", "Rarely (1 time/week)", "Sometimes (2-3 times/week)", "Often (4-5 times/week)", "Very Often (6 or more times/week)")

## Make the transformation now
cleaned_dataset <- cleaned_dataset %>%
  mutate(
    Prior_knowledge_I1 = as.numeric(factor(Prior_knowledge_Q1, levels = likert_scale, ordered = TRUE)),
    Prior_knowledge_I2 = as.numeric(factor(Prior_knowledge_Q2, levels = likert_scale, ordered = TRUE)),
    Prior_knowledge_I3 = as.numeric(factor(Prior_knowledge_Q3, levels = likert_scale, ordered = TRUE))
  )



#####################################
### CREATING AI DETECTION VARIABLE

## Note that we are creating this variable for eventual use in our mega-analysis
## Note that in this study, there was only one detection method (i.e. participant self-reporting)
## There was a prompt injection, but as mentioned in the supplement, it was quite crap

cleaned_dataset <- cleaned_dataset %>%
  mutate(chain_position_num = as.numeric(as.character(gen))) %>%                # Convert chain_position/gen to numeric for mathematical comparison
  mutate(                                                                       # Checking observations where participants self-reported AI usage
    used_AI_directly =  (AI_usage == "Yes"),
    used_AI_directly = replace_na(used_AI_directly, FALSE)                      # Catch any potential NAs generated by the logical checks
  ) %>%
  
  group_by(chain) %>%                                                           # Grouping by chain to calculate the temporal exposure of AI explanations to people who used AI + other people in the chain
  mutate(
    any_ai_in_chain = any(used_AI_directly),                                    # Did anyone in this specific chain use AI?
    first_ai_pos = ifelse(any_ai_in_chain,                                                        # If yes, what was the lowest (earliest) chain position where it happened?
                          min(chain_position_num[used_AI_directly == TRUE], na.rm = TRUE),         # If no one used it, assign 'Inf' (infinity) so it never triggers the next step
                          Inf),
    
    post_AI_introduction = ifelse(chain_position_num >= first_ai_pos, 1, 0),    # If the current position is >= the first AI position, they get a 1. Otherwise, 0.
    post_AI_introduction = as.factor(post_AI_introduction)
  ) %>%
  ungroup() %>%
  select(-chain_position_num, -any_ai_in_chain, -first_ai_pos)

#### SANITY CHECK to see if this variable was correctly created. 
## Creating a cross-tabulation of direct AI use vs. the new exposure variable: 

## Direct_AI_Use = TRUE & Post_AI_Status = 0: 
# This number MUST be 0. It is logically impossible for someone to have used AI directly but not be considered "post-AI introduction." 
# If there is a number here, the code broke

## Direct_AI_Use = TRUE & Post_AI_Status = 1: 
# This should perfectly match the total number of people who directly used AI (the rows in the ai_detection_comparison table).

## Direct_AI_Use = FALSE & Post_AI_Status = 0: 
# These are the "pure" observations—people in non-AI chains, plus the people sitting upstream in AI chains before the AI was introduced.
table(Direct_AI_Use = cleaned_dataset$used_AI_directly, 
      Post_AI_Status = cleaned_dataset$post_AI_introduction)





#####################################
### DATA DEMOGRAPHICS SUMMARY

## Providing descriptive statistics of the demographic and background variables
summary_df <- cleaned_dataset %>%
  group_by(gen) %>%
  summarise(
    Observations = n(),
    Age = round(mean(Age), 2),
    Sex = round((mean(Sex == "Female") * 100), 2),
    Prior_medication = round((mean(Prior_medication == "Yes") * 100), 2),
    Current_Treatment = round((mean(Current_Treatment == "Yes") * 100), 2),
    NHS_access = round((mean(NHS_try == "Yes") * 100), 2),
    AI = round((mean(AI_usage == "Yes") * 100), 2),
    Social_Media = round(mean(Prior_knowledge_I1), 2),
    NeuroDiv = round(mean(Prior_knowledge_I2), 2),
    Other_MHAware = round(mean(Prior_knowledge_I3), 2)
  )


## Defining a table theme for final table output
apa_theme <- function(ft, caption, stripe_rows = NULL,
                      spanner_cols = NULL, gap_cols = NULL, gap_width = 0.15) {
  ft <- ft |>
    border_remove() |>
    ## Thick rule above the header
    hline_top(part = "header", border = officer::fp_border(width = 1.5))
  
  ## Thin rule under each spanner; pass one range per spanner, e.g. list(4:8, 10:12)
  if (!is.null(spanner_cols)) {
    if (!is.list(spanner_cols)) spanner_cols <- list(spanner_cols)
    for (cols in spanner_cols) {
      ft <- hline(ft, i = 1, j = cols, part = "header",
                  border = officer::fp_border(width = 0.5))
    }
  }
  
  ft <- ft |>
    ## Rule separating header from body
    hline_bottom(part = "header", border = officer::fp_border(width = 0.75)) |>
    ## Thick rule closing the table
    hline_bottom(part = "body", border = officer::fp_border(width = 1.5))
  
  if (!is.null(stripe_rows)) {
    ft <- bg(ft, i = stripe_rows, bg = "#F5F5F5", part = "body")
  }
  
  ft <- ft |>
    set_caption(caption) |>
    font(fontname = "Times New Roman", part = "all") |>
    fontsize(size = 10, part = "all") |>
    padding(padding.top = 3, padding.bottom = 3, part = "all") |>
    autofit()
  
  ## Narrow the gap columns last, so autofit() can't undo it
  if (!is.null(gap_cols)) {
    ft <- ft |>
      padding(j = gap_cols, padding.left = 0, padding.right = 0, part = "all") |>
      width(j = gap_cols, width = gap_width)
  }
  
  ft
}


## Outputting the final demographics table
descriptive_ft <- summary_df |>
  tibble::add_column(gap = "", .after = "AI") |>              ## Added to distinguish the prior knowledge measures from the rest of the table
  flextable() |>
  set_header_labels(
    gen = "Chain position",
    Age = "Age (Mean)",
    Sex  = "Female (%)",
    Prior_medication = "MH Medication",
    Current_Treatment = "MH Treatment",
    NHS_access = "NHS MH Support",
    AI = "Self-Reported AI Use",
    gap = "",
    Social_Media = "Social Media",
    NeuroDiv = "Conversations",
    Other_MHAware = "Other Sources"
  ) |>
  add_header_row(
    values = c("", "Sample Characteristics (%)", "", "ADHD Prior Knowledge (M, 1-5)"),
    colwidths = c(3, 5, 1, 3)
  ) |>
  align(align = "center", part = "all") |>
  apa_theme(spanner_cols = list(4:8, 10:12),
            stripe_rows  = seq(2, nrow(summary_df), 2),
            caption = paste("Sample characteristics and ADHD/neurodiversity engagement by generation (Study 1)"))

descriptive_ft
  
  
  
  
  
  
    